api_token_env: CROWDIN_PERSONAL_TOKEN
project_id: 1
base_url: "https://discourse-test.crowdin.com"

preserve_hierarchy: false

files:
  - source: "/**/config/locales/server.en.yml"
    dest: "/%original_path%/server.yml"
    translation: "/%original_path%/server.%locale_with_underscore%.yml"
  - source: "/**/config/locales/client.en.yml"
    dest: "/%original_path%/client.yml"
    translation: "/%original_path%/client.%locale_with_underscore%.yml"
  - source: "/public/*[0-9].html"
    translation: "/%original_path%/%file_name%.%locale_with_underscore%.%file_extension%"

languages_mapping:
  locale_with_underscore:
    - "ar": "ar"
    - "de": "de"
    - "fr": "fr"
    - "hu": "hu"
    - "pt-BR": "pt_BR"
    - "zh-CN": "zh_CN"
