renames:
  # old_setting_name: new_setting_name
  security.use_https: security.force_https
  spam.num_flags_to_block_new_user: spam.num_spam_flags_to_block_new_user
  email.suppress_digest_email_after_days: email.delete_digest_email_after_days
  posting.ninja_edit_window: posting.editing_grace_period
  developer.max_tracked_new_unread: developer.max_new_topics
  posting.max_word_length: posting.title_max_word_lengt
  uncategorized.purge_inactive_users_grace_period_days: users.purge_unactivated_users_grace_period_days
  uncategorized.public_user_custom_fields: users.public_user_custom_fields
  trust.basic_requires_topics_entered: trust.tl1_requires_topics_entered
  trust.basic_requires_read_posts: trust.tl1_requires_read_posts
  trust.basic_requires_time_spent_mins: trust.tl1_requires_time_spent_mins
  trust.regular_requires_topics_entered: trust.tl2_requires_topics_entered
  trust.regular_requires_read_posts: trust.tl2_requires_read_posts
  trust.regular_requires_time_spent_mins: trust.tl2_requires_time_spent_mins
  trust.regular_requires_days_visited: trust.tl2_requires_days_visited
  trust.regular_requires_likes_received: trust.tl2_requires_likes_received
  trust.regular_requires_likes_given: trust.tl2_requires_likes_given
  trust.regular_requires_topic_reply_count: trust.tl2_requires_topic_reply_count
  trust.leader_requires_days_visited: trust.tl3_requires_days_visited
  trust.leader_requires_topics_replied_to: trust.tl3_requires_topics_replied_to
  trust.leader_requires_topics_viewed: trust.tl3_requires_topics_viewed
  trust.leader_requires_posts_read: trust.tl3_requires_posts_read
  trust.leader_requires_topics_viewed_all_time: trust.tl3_requires_topics_viewed_all_time
  trust.leader_requires_posts_read_all_time: trust.tl3_requires_posts_read_all_time
  trust.leader_requires_max_flagged: trust.tl3_requires_max_flagged
  trust.leader_promotion_min_duration: trust.tl3_promotion_min_duration
  trust.leader_requires_likes_given: trust.tl3_requires_likes_given
  trust.leader_requires_likes_received: trust.tl3_requires_likes_received
  trust.leader_links_no_follow: trust.tl3_links_no_follow
  email.pop3s_polling_enabled: email.pop3_polling_enabled
  email.pop3s_polling_insecure: email.pop3_polling_ssl
  email.pop3s_polling_period_mins: email.pop3_polling_period_mins
  email.pop3s_polling_host: email.pop3_polling_host
  email.pop3s_polling_port: email.pop3_polling_port
  email.pop3s_polling_username: email.pop3_polling_username
  email.pop3s_polling_password: email.pop3_polling_password
changes:
  1.1.0:
    added:
    - developer.background_polling_interval
    - developer.long_polling_base_url
    - developer.posts_chunksize
    - developer.verbose_localization
    - email.email_subject
    - email.enable_email_names
    - email.short_email_length
    - email.strip_images_from_short_emails
    - files.prevent_anons_from_downloading_files
    - login.forgot_password_strict
    - posting.censored_words
    - posting.delete_old_hidden_posts
    - posting.experimental_reply_expansion
    - posting.max_reply_history
    - security.cors_origins
    - uncategorized.summary_max_results
    - users.show_email_on_profile
    changed:
    - posting.post_edit_time_limit
    - developer.long_polling_interval
    - developer.anon_polling_interval
    - developer.flush_timings_secs
  1.1.1:
    added:
    - files.allow_animated_thumbnails
    - spam.max_new_accounts_per_registration_ip
    changed:
    - posting.default_code_lang
  1.2.0:
    added:
    - basic.category_style
    - email.disable_digest_emails
    - email.suppress_digest_email_after_days
    - login.enable_sso_provider
    - login.log_out_strict
    - posting.emoji_set
    - posting.enable_emoji
    - rate_limits.max_invites_per_day
    - spam.max_age_unmatched_emails
    - spam.max_age_unmatched_ips
    - spam.min_ban_entries_for_roll_up
    - spam.num_flaggers_to_close_topic
    - spam.num_flags_to_close_topic
    changed:
    - required.notification_email
    - basic.top_menu
    - basic.post_menu_hidden_items
  1.3.0:
    added:
    - files.avatar_sizes
    - files.default_avatars
    - files.s3_cdn_url
    - login.sso_not_approved_url
    - posting.approve_post_count
    - posting.approve_unless_trust_level
    - posting.enforce_square_emoji
    - posting.highlighted_languages
    - posting.min_first_post_length
    - posting.title_max_word_length
    - rate_limits.max_topic_invitations_per_day
    - rate_limits.tl2_additional_likes_per_day_multiplier
    - rate_limits.tl3_additional_likes_per_day_multiplier
    - rate_limits.tl4_additional_likes_per_day_multiplier
    - required.contact_url
    - required.exclude_rel_nofollow_domains
    - spam.auto_respond_to_flag_actions
    - uncategorized.delete_drafts_older_than_n_days
    - uncategorized.slug_generation_method
    - uncategorized.topic_view_duration_hours
    - users.allow_anonymous_posting
    - users.anonymous_account_duration_minutes
    - users.anonymous_posting_min_trust_level
    - users.enable_user_directory
    - users.full_name_required
    - users.staff_user_custom_fields
    changed:
    - basic.category_style
    - posting.post_edit_time_limit
    - files.max_attachment_size_kb
    - files.download_remote_images_threshold
    - files.clean_up_uploads
    - files.s3_region
    - files.allow_animated_thumbnails
    - uncategorized.cold_age_days_medium
    - uncategorized.cold_age_days_high
  1.4.0:
    added:
    - backups.automatic_backups_enabled
    - backups.backup_frequency
    - basic.enable_whispers
    - basic.fixed_category_positions_on_create
    - developer.max_tracked_new_unread
    - developer.migrate_to_new_scheme
    - email.log_mail_processing_failures
    - files.external_system_avatars_enabled
    - files.external_system_avatars_url
    - login.enable_signup_cta
    - posting.allow_html_tables
    - posting.notify_about_queued_posts_after
    - posting.show_time_gap_days
    - spam.auto_block_fast_typers_max_trust_level
    - spam.auto_block_fast_typers_on_first_post
    - spam.auto_block_first_post_regex
    - spam.min_first_post_typing_time
    - uncategorized.daily_performance_report
    - uncategorized.min_new_topics_time
    - uncategorized.performance_report_topic_id
    - uncategorized.permalink_normalizations
    - uncategorized.show_logout_in_header
    - uncategorized.uncategorized_category_id
    - user_preferences.default_categories_muted
    - user_preferences.default_categories_tracking
    - user_preferences.default_categories_watching
    - user_preferences.default_email_always
    - user_preferences.default_email_digest_frequency
    - user_preferences.default_email_direct
    - user_preferences.default_email_mailing_list_mode
    - user_preferences.default_email_private_messages
    - user_preferences.default_other_auto_track_topics_after_msecs
    - user_preferences.default_other_disable_jump_reply
    - user_preferences.default_other_dynamic_favicon
    - user_preferences.default_other_edit_history_public
    - user_preferences.default_other_enable_quoting
    - user_preferences.default_other_external_links_in_new_tab
    - user_preferences.default_other_new_topic_duration_minutes
    - users.reserved_usernames
    changed:
    - basic.post_menu
    - posting.newuser_max_images
    - rate_limits.rate_limit_new_user_create_topic
    - rate_limits.max_topics_in_first_day
    - developer.flush_timings_secs
    - uncategorized.max_similar_results
    - uncategorized.vacuum_db_days
  1.5.0:
    added:
    - backups.backup_time_of_day
    - backups.backup_with_uploads
    - backups.s3_disable_cleanup
    - basic.set_locale_from_accept_language_header
    - basic.top_page_default_timeframe
    - developer.top_topics_formula_first_post_likes_multiplier
    - developer.top_topics_formula_least_likes_per_post_multiplier
    - developer.top_topics_formula_log_views_multiplier
    - email.delete_email_logs_after_days
    - email.digest_suppress_categories
    - email.display_name_on_email_from
    - email.enable_staged_users
    - email.manual_polling_enabled
    - email.max_emails_per_day_per_user
    - email.private_email_time_window_seconds
    - email.unsubscribe_via_email
    - email.unsubscribe_via_email_footer
    - embedding.embed_classname_whitelist
    - files.allow_all_attachments_for_group_messages
    - files.default_opengraph_image_url
    - login.enable_instagram_logins
    - login.instagram_consumer_key
    - login.instagram_consumer_secret
    - login.pending_users_reminder_delay
    - posting.allow_uppercase_posts
    - posting.max_users_notified_per_group_mention
    - rate_limits.alert_admins_if_errors_per_hour
    - rate_limits.alert_admins_if_errors_per_minute
    - security.use_admin_ip_whitelist
    - trust.min_trust_to_allow_self_wiki
    - trust.min_trust_to_send_messages
    - trust.tl3_time_period
    - uncategorized.automatically_unpin_topics
    - uncategorized.disable_avatar_education_message
    - uncategorized.read_time_word_count
    - uncategorized.search_tokenize_chinese_japanese_korean
    - uncategorized.user_profile_view_duration_hours
    - user_preferences.default_email_in_reply_to
    - user_preferences.default_email_previous_replies
    - user_preferences.default_include_tl0_in_digests
    - user_preferences.default_other_like_notification_frequency
    - user_preferences.default_topics_automatic_unpin
    - user_preferences.disable_mailing_list_mode
    - users.hide_user_profiles_from_public
    - users.min_admin_password_length
    changed:
    - users.min_password_length
    - users.purge_unactivated_users_grace_period_days
    - files.external_system_avatars_url
    - backups.maximum_backups
    - user_preferences.default_email_digest_frequency
  1.6.0:
    added:
    - backups.readonly_mode_during_backup
    - basic.enable_badge_sql
    - basic.gtm_container_id
    - basic.suggested_topics_max_days_old
    - email.alternative_reply_by_email_addresses
    - email.attachment_content_type_blacklist
    - email.attachment_filename_blacklist
    - email.auto_generated_whitelist
    - email.block_auto_generated_emails
    - email.bounce_score_threshold
    - email.bounce_score_threshold_deactivate
    - email.hard_bounce_score
    - email.ignore_by_title
    - email.incoming_email_prefer_html
    - email.mailgun_api_key
    - email.maximum_staged_users_per_email
    - email.reset_bounce_score_after_days
    - email.soft_bounce_score
    - files.convert_pasted_images_quality
    - files.convert_pasted_images_to_hq_jpg
    - files.download_remote_images_max_days_old
    - login.maximum_session_age
    - login.sso_overrides_bio
    - login.verbose_sso_logging
    - posting.auto_close_messages_post_count
    - posting.auto_close_topics_post_count
    - posting.code_formatting_style
    - posting.show_pinned_excerpt_desktop
    - posting.show_pinned_excerpt_mobile
    - spam.num_tl3_flags_to_block_new_user
    - spam.num_tl3_users_to_block_new_user
    - tags.max_tag_length
    - tags.max_tag_search_results
    - tags.max_tags_in_filter_list
    - tags.max_tags_per_topic
    - tags.min_trust_level_to_tag_topics
    - tags.min_trust_to_create_tag
    - tags.remove_muted_tags_from_latest
    - tags.show_filter_by_tag
    - tags.staff_tags
    - tags.suppress_overlapping_tags_in_list
    - tags.tag_style
    - tags.tagging_enabled
    - tags.tags_sort_alphabetically
    - trust.tl3_requires_posts_read_cap
    - trust.tl3_requires_topics_viewed_cap
    - uncategorized.bootstrap_mode_enabled
    - uncategorized.bootstrap_mode_min_users
    - uncategorized.topic_page_title_includes_category
    - user_preferences.default_email_mailing_list_mode_frequency
    - users.prioritize_username_in_ux
    changed:
    - basic.post_menu_hidden_items
    - basic.share_links
    - users.email_token_valid_hours
    - files.clean_orphan_uploads_grace_period_hours
    - spam.flag_sockpuppets
